### ISSUE TITLE
Broken generated URL

### ISSUE THREAD

**Issue by paddykily** [theapache64/coin_hive_android_sdk#10]
I'm getting the following error:

The requested URL /coinhive/engine.html was not found on this server.
http://theapache64.com:8090/coinhive/engine.html?coinhive_site_key=[SITE_KEY]&num_of_threads=4&is_auto_thread=true&throttle=0.2

**Comment by josue-armenta** [comment]
Just tried today to run the miner and the same happened!

**Comment by theapache64** [comment]
It was some kind of server glitch. but don't worry, i've fixed it. thank you for notification. :) :peace_symbol:

**Comment by hwaliashraf** [comment]
having same issue as of now
any solution or how could I help?
