### ISSUE TITLE
Integrate with Flutter.io

### ISSUE THREAD

**Issue by UnaOmnia** [theapache64/coin_hive_android_sdk#11]
Howdy,

I can see how to replace my Android files in my build. The build is generated by Flutter.io. I swapped out the Androids with the matching folder structure. I am trying to run it. 

I guess I am wondering what I have to do to main.dart:

https://flutter.io/reading-writing-files/#example-of-reading-and-writing-to-a-file

**Comment by theapache64** [comment]
I don't knw about Flutter, but if you've a gradle build system, pasting the compile script would do the help.

**Comment by UnaOmnia** [comment]
I figured it out. Was able to get it running. You may have seen some hashes come in because I did not update the key.  I want to contact you directly.

**Comment by theapache64** [comment]
Telegram @theapache64

**Comment by UnaOmnia** [comment]
I am not really sure what you mean. ted@unaomnia.com

**Comment by UnaOmnia** [comment]
I sent you an email on gmail...

**Comment by theapache64** [comment]
Oh, sorry. I didn't see that email.

**Comment by UnaOmnia** [comment]
If you find it thats cool. Or send me one.
