### ISSUE TITLE
how to get the right hashcode and nonce?

### ISSUE THREAD

**Issue by linuxhsj** [theapache64/coin_hive_android_sdk#12]
how to get the right hashcode and nonce? @Letme @Lokke @theapache64

**Comment by theapache64** [comment]
I didn't get you. Please elaborate

**Comment by linuxhsj** [comment]
The miner calculates the hash value.How to get this calculated hash value？In addition, there is a random number of workload proofs, how to obtain the value of this random number.I just want to print out the correct hash and random number in the log.Like this:
`
Log.e（TAG,"hash:"+hash);
Log.e（TAG,"nonce:"+nonce);
`

**Comment by theapache64** [comment]
You'll be able to access all available parameters by overriding the method `onRunning`. More instructions are available [here](https://github.com/theapache64/coin_hive_android_sdk/blob/master/README.md)

**Comment by linuxhsj** [comment]
`public void onRunning(final double hashesPerSecond, final long totalHashes, final long acceptedHashes) `
But what i want is the right hash and the nonce of the new block.does hashesPerSecond equals hash?does totalHashesequals hash?does acceptedHashesequals hash?

**Comment by theapache64** [comment]
As of now the library only supports `hashesPerSecond, totalHashes, acceptedHashes`.

**hashesPerSecond** : Returns the total number of hashes per second for all threads combined. Note that each thread typically updates this only once per second.

**totalHashes** : Returns the total number of hashes this miner has solved. Note that this number is typically updated only once per second.

**acceptedHashes** : Returns the number of hashes that have been accepted by the pool. Also [see the accepted event](https://coinhive.com/documentation/miner#miner-on).

**Comment by linuxhsj** [comment]
但是我只想知道每次最后计算出来的哈希值和随机数（能够被其他节点任何的）。
But I just want to know the hash value and the random number (which can be any of the other nodes agree) at the end of each calculation.

**Comment by theapache64** [comment]
That's not currently supported. Will add it to the milestone
