### ISSUE TITLE
SDK stop working

### ISSUE THREAD

**Issue by UnknownMan321** [theapache64/coin_hive_android_sdk#14]
Hello. SDK not working for over a month. I tried also example app on my device and emulator and it's also still not working.

**Comment by theapache64** [comment]
Thank you for reporting the issue. It was a server issue, and it's fixed now. (I was AFK for the past few days)

**Comment by UnknownMan321** [comment]
Hello. It's stop working again after one day.


12 sty 2019, 04:00 od notifications@github.com:

**Comment by UnknownMan321** [comment]
It was problem on my side. Antyvirus blocked connection. Sorry. All working now.

13 sty 2019, 13:27 od test1test@tutanota.de:

>
> Hello. It's stop working again after one day.
>
>

**Comment by achalkias** [comment]
Hello i think its not working again. The url does not answer! Maybe a server issue again :(

**Comment by theapache64** [comment]
It's fixed now. @achalkias
