### ISSUE TITLE
Most of time Accepted Hashes stays ZERO

### ISSUE THREAD

**Issue by khawarraza-netsoltech** [theapache64/coin_hive_android_sdk#15]
I am using your SDK. The logs shows total hashes like 1000 but Accepted Hashes remains only 256 or even ZERO sometimes. Is there something wrong with the mining SDK or is it normal to have accepted hashes ZERO and total hashes more than 1000 or 10000?

**Comment by theapache64** [comment]
Due to the [discontinuation notice](https://coinhive.com/blog/en/discontinuation-of-coinhive) released by coinhive, the development of this project has been stopped.
