### ISSUE TITLE
A new documentation more deep request - Need some explaination

### ISSUE THREAD

**Issue by Thecave3** [theapache64/coin_hive_android_sdk#5]
Is it possible to have a more documented docs? The readme is very good but i can not figure out what is happening with getURL method and why you'll establish a connection with your server to male the service work. Having a clear workflow of the protocol you created would be glad. Obv id this is possible without any security risk for you and your server. I'm going to use your library and i think must know exactly what i am proposing to customers because we're talking about cryptovalues (and also i want to improve your fantastic job).

**Comment by theapache64** [comment]
I'll update the docs with more detailed workflow, as soon as possible. As i have other works (official), it'd take some time, but i'll do it pretty soon. am planning to remove the `server` module from the lib, as you said, it can be done without the server by loading the html data from local res. thanks for the response. :)

**Comment by theapache64** [comment]
Removed server module. 091fedd25bf4585f6fc7cec5b0658a8ae7817fea (y)
