### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by KeizerDev** [theapache64/coin_hive_android_sdk#8]
Is it possible to keep this running on the background?

**Comment by theapache64** [comment]
Yeah, it’ll run in the background untill the activity get destoryed

**Comment by KeizerDev** [comment]
I want to keep it running as a service. Is that possible?

**Comment by theapache64** [comment]
am sorry. as of now, background mining is not supported by this library.

**Comment by islomov** [comment]
When you will implement this type of feature

**Comment by kirill578** [comment]
@fironjon port it into an service shouldn't be too much of a problem, just copy the source from `BaseCoinHiveActivity` to an `IntentService`. Note that adding the view to a viewgroup is not mandatory.

Please keep in mind, that Android Oreo introduced `startForground()` which is mandatory, and results in a persistent notification that shows that your app is running in the background.
